<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <InvariantGlobalization>true</InvariantGlobalization>
        <!--        <InvariantGlobalization>false</InvariantGlobalization>-->
        <!--        <WasmIncludeFullIcuData>true</WasmIncludeFullIcuData>-->
        <!--        <WasmIcuDataFileName>icudt.dat</WasmIcuDataFileName>-->
        <!--        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>-->
        <WasmAllowUndefinedSymbols>true</WasmAllowUndefinedSymbols>
        <EmccInitialHeapSize>128MB</EmccInitialHeapSize>
        <SkiaUseGraphite>False</SkiaUseGraphite>
        <RootNamespace>AppBoxDesign</RootNamespace>
        <AssemblyName>AppBoxStudio.Web</AssemblyName>
        <RunAOTCompilation>true</RunAOTCompilation>
        <StaticWebAssetBasePath>dev</StaticWebAssetBasePath>
    </PropertyGroup>

    <Import Project="../../ext/PixUI/src/PixUI.Drawing.Skia/Native/Wasm.targets"/>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\ext\PixUI\ext\LiveCharts2\src\LiveChartsCore\LiveChartsCore.csproj"/>
        <ProjectReference Include="..\..\ext\PixUI\src\PixUI.LiveCharts\PixUI.LiveCharts.csproj"/>
        <ProjectReference Include="..\..\ext\PixUI\src\PixUI\PixUI.csproj"/>
        <ProjectReference Include="..\AppStudio\AppStudio.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\..\ext\PixUI\src\PixUI.Platform.Blazor\WebApplication.cs">
            <Link>WebApplication.cs</Link>
        </Compile>
        <Compile Include="..\..\ext\PixUI\src\PixUI.Platform.Blazor\WebClipboard.cs">
            <Link>WebClipboard.cs</Link>
        </Compile>
        <Compile Include="..\..\ext\PixUI\src\PixUI.Platform.Blazor\WebCursors.cs">
            <Link>WebCursors.cs</Link>
        </Compile>
        <Compile Include="..\..\ext\PixUI\src\PixUI.Platform.Blazor\WebFileDialog.cs">
            <Link>WebFileDialog.cs</Link>
        </Compile>
        <Compile Include="..\..\ext\PixUI\src\PixUI.Platform.Blazor\WebWindow.cs">
            <Link>WebWindow.cs</Link>
        </Compile>
        <Compile Include="..\..\ext\PixUI\src\PixUI.Platform.Blazor\WebGLWindow.cs">
            <Link>WebGLWindow.cs</Link>
        </Compile>
        <Compile Include="..\..\ext\PixUI\src\PixUI.Platform.Blazor\WebGPUWindow.cs">
            <Link>WebGPUWindow.cs</Link>
        </Compile>
        <Compile Include="..\..\ext\PixUI\src\PixUI.Platform.Blazor\InputUtils.cs">
            <Link>InputUtils.cs</Link>
        </Compile>
        <Compile Include="..\..\ext\PixUI\src\PixUI.Platform.Blazor\WebBrowser.cs">
            <Link>WebBrowser.cs</Link>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Microsoft.CodeAnalysis">
            <HintPath>..\..\ext\Roslyn\Microsoft.CodeAnalysis.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.CSharp">
            <HintPath>..\..\ext\Roslyn\Microsoft.CodeAnalysis.CSharp.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.CSharp.Features">
            <HintPath>..\..\ext\Roslyn\Microsoft.CodeAnalysis.CSharp.Features.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.CSharp.Workspaces">
            <HintPath>..\..\ext\Roslyn\Microsoft.CodeAnalysis.CSharp.Workspaces.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.Elfie">
            <HintPath>..\..\ext\Roslyn\Microsoft.CodeAnalysis.Elfie.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.Features">
            <HintPath>..\..\ext\Roslyn\Microsoft.CodeAnalysis.Features.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.Scripting">
            <HintPath>..\..\ext\Roslyn\Microsoft.CodeAnalysis.Scripting.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.Workspaces">
            <HintPath>..\..\ext\Roslyn\Microsoft.CodeAnalysis.Workspaces.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
