export enum DataFieldType {
    EntityId = 0,
    String = 1,
    DateTime = 2,
    Short = 4,
    Int = 6,
    Long = 8,
    Decimal = 9,
    Bool = 10,
    Guid = 11,
    Byte = 12,
    Binary = 13,
    Enum = 14,
    Float = 15,
    Double = 16,
}